name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build-and-test:
    name: Build and test on Ubuntu - Node 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      # Build and test Multinet client app.
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # Build and test Multinet client library.
      - uses: actions/cache@v1
        id: multinetjs-cache
        with:
          path: /home/runner/work/multinetjs/multinetjs/node_modules
          key: ${{ runner.os }}-${{ hashFiles('/home/runner/work/multinetjs/multinetjs/yarn.lock') }}-multinetjs-cache

      - name: Install yarn packages
        if: steps.multinetjs-cache.outputs.cache-hit != 'true'
        run: yarn install

      - run: yarn build
      - run: yarn lint

      - name: Get the version number
        id: version-number
        run: echo "::set-output name=version::$(git describe --tags | tail -c +2)"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Publish the package
        run: yarn publish --new-version ${{ steps.version-number.outputs.version }} --non-interactive --no-git-tag-version
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
